apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tara1
spec:
  destination:
    name: zuscu-d006-b207-aks-d1-atldp
    namespace: tara1
  source:
    path: guestbook
    repoURL: 'https://github.com/it2008018/guestbook-Tara.git/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
