apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taramanual
spec:
  destination:
    name: durablefnks
    namespace: taramanual
  source:
    path: guestbook
    repoURL: 'https://github.com/it2008018/guestbook-Tara.git/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
